## Stage 1: Build the manager binary
FROM registry.redhat.io/ubi9/go-toolset@sha256:685ccca486cc2c82b0818d835abecb1aed7a396e76ba416cfc47c28067f5d365 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY cmd/main.go cmd/main.go
COPY api/ api/
COPY internal/ internal/

USER root
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -tags strictfipsruntime -a -ldflags="-s -w" -o manager cmd/main.go

## Stage 2: Runtime
FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:a3f7ca6346ee5ca1867d1dcc79b011c5c711bf7a3e43c7cece3323d6d1ef5ac0

WORKDIR /
COPY --from=builder /workspace/manager .
COPY opt/manifests /opt/manifests
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-workbenches-operator-rhel9 " \
      name="rhoai/odh-workbenches-operator-rhel9 " \
      description="odh-workbenches-operator" \
      summary="odh-workbenches-operator" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-workbenches-operator" \
      io.k8s.description="odh-workbenches-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
