name: Build

on:
  push:
    branches: [main, stable, v1.x]
  pull_request:
    branches: [main, stable, v1.x]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@v7
        with:
          check-latest: true
          go-version-file: go.mod

      - name: Generate and build
        run: make build
